### ISSUE TITLE
Comments are not showing on task's box

### ISSUE THREAD

**Issue by guerra** [eubr-bigsea/citron#175]
When you type some text in the comment field on task's form, it's not shown on the box designed for it (inside task's frame).

**Comment by ojvictor** [comment]
The comments are showing inside the task box, but the comment field remains empty. The comment box should retrieve/store the comments too because helps the user edit the message. 
![task_empty_field](https://user-images.githubusercontent.com/6419508/27589261-382dac24-5b21-11e7-9d51-39d62bc1a757.png)
