### ISSUE TITLE
If user authentication is persisted and there is an error in any API call, app display a blank screen

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citron#234]
For example, if there is an error in Tahiti or Stand, application does not work anymore. It may be caused because there is an old auth_token with wrong user id information. But most important, Citron must handle such back-end reported errors.

If you remove localStorage information (see how to do it in browsers), it works.

**Comment by mgonc** [comment]
@waltersf this error occurs because of the status error that server respond. Stand is send a 401 Unauthorized when missing json parameters for example. Then ember-simple-auth handle 401 invalidating session. On tahiti server is current not throwing errors, ngix is sending a HTML response with message "Sorry, the page you are looking for is currently unavailable.". I will create issues on both services and create issue here in citron to handle api response errors.

**Comment by waltersf** [comment]
Fixed in Stand. However, Citron must handle errors from back-end. For example, if I stop stand service, Citron will display the blank screen again. Maybe @michelboaventura knows a way to handle all errors in Ember and how to redirect when unexpected errors happen.
