### ISSUE TITLE
Visualization library is not compatible with Ember minifier

### ISSUE THREAD

**Issue by waltersf** [eubr-bigsea/citron#243]
Visualization library (Geraldo's gViz) is not being minified correctly because there are some code checked during minifying time and it is always resolved as false:
```
var container = undefined;
...
case 'build':
    return container != null && $(container).length !== 0;
```
The `case` is resolved as `false`.

Solution could be remove gViz source files from process. See my branch ws_disable_minify_gviz. But try  better solutions, if possible.

**Comment by gfranciscani** [comment]
That issue was already reported and our suggestion was the same: for dev and test versions, use unminified version of the library. For production, compile the code separately and use it as a vendor library, like JQuery.

**Comment by michelboaventura** [comment]
I don't think it has been reported before. In the past we had issues with the gViz being written in es6 and babel had trouble with it. Now we found an invalid JS which optimizes itself in a way that broke the visualizations.

The problem is that ``container`` is defined as ``undefined`` and never changed again on the code. I think @gfranciscani uses a couple of ``eval``s to export ``container`` as a global variable, but the optimize has no way to guess that.

I don't know an easy way to solve this without ignoring minifying or change the evals. I also don't know if ``js`` has a ``volatile`` attribute as in ``C``.

**Comment by gfranciscani** [comment]
`container` is one of the exposed variables of the closure (as many others), not defined as global. The value `undefined` is its default value and only happens if it is not passed as an argument for the chart function. It must not be changed in the visualizations code, but only for the user that will set it as a parameter with reference for the container of the div.

Moreover, the `evals` can be broken into multiple variables declarations, if it is the reason of the problem.
