### ISSUE TITLE
System freezes when uploading medium size data files

### ISSUE THREAD

**Issue by quigonjeff** [eubr-bigsea/citron#418]
I was able to upload two data files with size smaller than 1MB but when I try to upload my real data file, with size 61MB, the system stops. The dialog message in the bottom left corner of the page progresses until it says the file is 100% loaded, but then the dialog does not close, and the system seems to freeze. No error message, nothing. Just freezes. I was waiting for about 30min, then I closed the window.

**Comment by waltersf** [comment]
Hi, @quigonjeff ,

I checked the installation and there was a missing configuration, thanks for reporting. We're using nginx as web server and there is a special configuration for file uploading: 

`client_max_body_size 2M;`

We changed it to 2Mb and it seems to be working. Please, let us know if the problem persists, otherwise, you may close the issue.

[]

**Comment by quigonjeff** [comment]
I confirm it is working now. I successfully upload the file I was trying earlier. Thanks.

**Comment by guerra** [comment]
@waltersf, can I close this issue?
