### ISSUE TITLE
Execute SQL query box - "Names of attributes after the query"

### ISSUE THREAD

**Issue by SergioSJS** [eubr-bigsea/citron#450]
If I typing something in "Names of attributes after the query" field and to erase the field, in execute, the system return the error:

> Invalid or missing parameters: Invalid names. Number of attributes in result differs from names informed.

Even the field being empty.

**Comment by mgonc** [comment]
can you pass me the id of workflow that happened?

**Comment by waltersf** [comment]
@mgonc I'm fixing it now. It's a problem in juicer.

**Comment by waltersf** [comment]
Now the behavior is correct:
- If you define the names, the number must be the same as the columns produced by SQL and names are used for attribute suggestion.
- If names are not defined (empty), it uses the aliases/names from query (but not for attribute suggestion, because it is not possible to compute them without running the workflow).
