### ISSUE TITLE
Slow Operation's sidebar rendering

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/citron#511]
The operation's sidebar takes some seconds to refresh when the user changes from one box to another.

**Comment by waltersf** [comment]
It seems to be a problem partially caused by Limonero. The data sources query is taking longer than it should. I optimized the query, but the problem seems to be in the container. From the Citron side, I think we should block the UI until the request finishes (showing a loading image or something like this). Other environments aren't facing this problem, only test one.
